plugins {
    id "base"
    id "org.springframework.boot" version "4.0.6" apply false
    id "io.spring.dependency-management" version "1.1.7" apply false
    id "io.freefair.lombok" version "9.5.0" apply false
}

group "org.abondar.experimental.shoppingcart"
version "2.0"

def serviceProjects = [
        project(":cart-service"),
        project(":product-service")
]

configure(serviceProjects) {
    apply plugin: "java"
    apply plugin: "idea"
    apply plugin: "org.springframework.boot"
    apply plugin: "io.spring.dependency-management"
    apply plugin: "io.freefair.lombok"

    group = rootProject.group
    version = rootProject.version

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        implementation(project(":shared"))

        implementation("org.springframework.boot:spring-boot-starter-web")
        implementation("org.springframework.boot:spring-boot-starter-actuator")
        implementation("org.springframework.boot:spring-boot-starter-validation")

        implementation("org.apache.camel.springboot:camel-spring-boot-starter:$camelVersion")
        implementation("org.apache.camel.springboot:camel-jackson3-starter:$camelVersion")
        implementation("org.apache.camel.springboot:camel-platform-http-starter:$camelVersion")
        implementation("org.apache.camel.springboot:camel-springdoc-starter:$camelVersion")
        implementation("org.apache.camel.springboot:camel-bean-validator-starter:$camelVersion")

        testImplementation("org.springframework.boot:spring-boot-starter-test")
        testImplementation("org.springframework.boot:spring-boot-starter-restclient-test")
        testImplementation("org.apache.camel:camel-test-spring-junit5:$camelVersion")
    }

    tasks.named("test") {
        useJUnitPlatform()
    }
}

tasks.named("build") {
    dependsOn(
            ":shared:build",
            ":cart-service:build",
            ":product-service:build"
    )
}

tasks.register("test") {
    group = "verification"
    description = "Runs tests for all Gradle subprojects."
    dependsOn(
            ":shared:test",
            ":cart-service:test",
            ":product-service:test"
    )
}
