spring:
  application:
    name: ShoppingCart
  main:
    banner-mode: "console"


camel:
  servlet:
    mapping:
      context-path: /api/*

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      status:
        order: DOWN,OUT_OF_SERVICE,UP

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus



