package org.abondar.experimental.shoppingcart.product;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;
import org.springframework.stereotype.Component;


@Component
public class ProductRestRoute extends RouteBuilder {
    @Override
    public void configure() {
        rest()
                .path("/v1/products")
                .consumes("application/json")
                .produces("application/json")

                .post()
                .description("Create a new product")
                .apiDocs(true)
                .type(ProductCreateUpdateRequest.class)
                .outType(ProductResponse.class)
                .responseMessage()
                .code(201)
                .message("Product created")
                .endResponseMessage()
                .responseMessage()
                .code(400)
                .message("Invalid product request")
                .endResponseMessage()
                .to("direct:createProduct")

                .put("/{id}")
                .description("Update an existing product")
                .apiDocs(true)
                .type(ProductCreateUpdateRequest.class)
                .outType(ProductResponse.class)
                .param()
                .name("id")
                .type(RestParamType.path)
                .description("Product identifier")
                .required(true)
                .endParam()
                .responseMessage()
                .code(200)
                .message("Product updated")
                .endResponseMessage()
                .responseMessage()
                .code(400)
                .message("Invalid product request")
                .endResponseMessage()
                .responseMessage()
                .code(404)
                .message("Product not found")
                .endResponseMessage()
                .to("direct:updateProduct")

                .get("/{id}")
                .description("Get product by id")
                .apiDocs(true)
                .outType(ProductResponse.class)
                .param()
                .name("id")
                .type(RestParamType.path)
                .description("Product identifier")
                .required(true)
                .endParam()
                .responseMessage()
                .code(200)
                .message("Product found")
                .endResponseMessage()
                .responseMessage()
                .code(404)
                .message("Product not found")
                .endResponseMessage()
                .to("direct:getProductById")

                .get()
                .description("Get paginated list of products")
                .apiDocs(true)
                .param()
                .name("limit")
                .type(RestParamType.query)
                .description("Maximum number of products to return")
                .required(false)
                .dataType("integer")
                .endParam()
                .param()
                .name("offset")
                .type(RestParamType.query)
                .description("Number of products to skip")
                .required(false)
                .dataType("integer")
                .endParam()
                .outType(ProductListResponse.class)
                .responseMessage()
                .code(200)
                .message("Products fetched")
                .endResponseMessage()
                .responseMessage()
                .code(400)
                .message("Invalid pagination parameters")
                .endResponseMessage()
                .to("direct:getProducts")

                .delete("/{id}")
                .description("Delete product by id")
                .apiDocs(true)
                .param()
                .name("id")
                .type(RestParamType.path)
                .description("Product identifier")
                .required(true)
                .endParam()
                .responseMessage()
                .code(204)
                .message("Product deleted")
                .endResponseMessage()
                .responseMessage()
                .code(404)
                .message("Product not found")
                .endResponseMessage()
                .to("direct:deleteProduct");
    }
}