package org.abondar.experimental.shoppingcart.cart;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;
import org.springframework.stereotype.Component;

@Component
public class CartRestRoute extends RouteBuilder {
    @Override
    public void configure() {

        rest()
                .path("/v1/carts")
                .produces("application/json")

                .post()
                .description("Create a new shopping cart")
                .apiDocs(true)
                .outType(CartResponse.class)
                .responseMessage()
                .code(201)
                .message("Cart created")
                .endResponseMessage()
                .to("direct:createCart")

                .get("/{id}")
                .description("Get cart by id")
                .apiDocs(true)
                .outType(CartResponse.class)
                .param()
                .name("id")
                .type(RestParamType.path)
                .description("Cart identifier")
                .required(true)
                .endParam()
                .responseMessage()
                .code(200)
                .message("Cart found")
                .endResponseMessage()
                .responseMessage()
                .code(404)
                .message("Cart not found")
                .endResponseMessage()
                .to("direct:getCart")

                .post("/{id}/items")
                .description("Add product to cart")
                .apiDocs(true)
                .type(CartItemAddRequest.class)
                .outType(CartResponse.class)
                .param()
                .name("id")
                .type(RestParamType.path)
                .description("Cart identifier")
                .required(true)
                .endParam()
                .responseMessage()
                .code(200)
                .message("Item added to cart")
                .endResponseMessage()
                .responseMessage()
                .code(400)
                .message("Invalid cart item request")
                .endResponseMessage()
                .responseMessage()
                .code(404)
                .message("Cart or product not found")
                .endResponseMessage()
                .to("direct:addCartItem")

                .patch("/{id}/items/{productId}")
                .description("Update quantity of product in cart")
                .apiDocs(true)
                .type(CartItemUpdateQuantityRequest.class)
                .outType(CartResponse.class)
                .param()
                .name("id")
                .type(RestParamType.path)
                .description("Cart identifier")
                .required(true)
                .endParam()
                .param()
                .name("productId")
                .type(RestParamType.path)
                .description("Product identifier")
                .required(true)
                .endParam()
                .responseMessage()
                .code(200)
                .message("Cart item updated")
                .endResponseMessage()
                .responseMessage()
                .code(400)
                .message("Invalid quantity update request")
                .endResponseMessage()
                .responseMessage()
                .code(404)
                .message("Cart or product not found")
                .endResponseMessage()
                .to("direct:updateCartItem")

                .delete("/{id}/items/{productId}")
                .description("Remove product from cart")
                .apiDocs(true)
                .outType(CartResponse.class)
                .param()
                .name("id")
                .type(RestParamType.path)
                .description("Cart identifier")
                .required(true)
                .endParam()
                .param()
                .name("productId")
                .type(RestParamType.path)
                .description("Product identifier")
                .required(true)
                .endParam()
                .responseMessage()
                .code(200)
                .message("Cart item deleted")
                .endResponseMessage()
                .responseMessage()
                .code(404)
                .message("Cart or product not found")
                .endResponseMessage()
                .to("direct:deleteCartItem")

                .delete("/{id}")
                .description("Delete cart by id")
                .apiDocs(true)
                .param()
                .name("id")
                .type(RestParamType.path)
                .description("Cart identifier")
                .required(true)
                .endParam()
                .responseMessage()
                .code(204)
                .message("Cart deleted")
                .endResponseMessage()
                .responseMessage()
                .code(404)
                .message("Cart not found")
                .endResponseMessage()
                .to("direct:deleteCart");
    }
}